name: Deploy to Cloud Run on push to main

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: finanzas-ok-8c956
          install_components: "beta"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker gcr.io

      - name: Docker Build
        run: docker build --platform=linux/amd64 -t gcr.io/finanzas-ok-8c956/finanzas-ok-backend .

      - name: Push Docker Image
        run: docker push gcr.io/finanzas-ok-8c956/finanzas-ok-backend:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy finanzas-ok-backend \
            --image gcr.io/finanzas-ok-8c956/finanzas-ok-backend:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --clear-env-vars \
            --set-secrets JWT_SECRET=jwt-secret:latest,MONGO_URI=mongo-uri:latest,MAILGUN_API_KEY=mailgun-api-key:latest,WEBAUTHN_RP_ID=webauthn-rp-id:latest

      - name: Notify Discord on Success
        if: success()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Finanzas Smart Severless Deployment to Cloud Run was **successful**! 🚀"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on Failure
        if: failure()
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"content": "Finanzas Smart Severless Deployment to Cloud Run **failed**. Please check the workflow logs for more details. ⚠️"}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
